### ISSUE TITLE
Why we need many sequences?

### ISSUE THREAD

**Issue by al33m501** [fmorenopino/HeterogeneousHMM#6]
Hi! I carefully read the full [example](https://github.com/fmorenopino/HeterogeneousHMM/blob/master/examples/hmm_tutorials.ipynb), and my question is about part `HMM with labels`. 

I the sample dataset, we have 10 sequences split by time. Why do we need to do this, what's the purpose?

**Comment by fmorenopino** [comment]
Hi!

Not sure I understood your question correctly. In case you are wondering why we are using >1 sequence to learn the model's parameters (instead of just one), the answer is analogous to the training of any ML method. For the specific case of the HHMM, you could learn its parameters by just using one sequence, as you mentioned, but the ability of a model trained with that small amount of data to generalise would be very poor.

Anyhow, the examples from that notebook illustrate how to perform the most simple tasks that the library allows you. In a realistic setup, you would use as much data as possible.

**Comment by al33m501** [comment]
@fmorenopino Sorry, it seems like I described the question inaccurately. In example we use 10 sequences with shapes (286,5) each one. Why we cant just use one sequence with shape (2860,5)?

**Comment by fmorenopino** [comment]
Understood! You could fit the model by using the one sequence that includes the other 10 sub-sequences. Using a separate dimension (besides time) to index different sequences is a software-design choice that facilitates dealing with your data before training the model.

Sometimes you may wish to divide your sequence of duration T in (let's say) 10 sequences of duration T/10 each. Other times, you have different sequences with no particular order. In this case, it does not seems best to force users to join all those different sequences along their time axis.

I hope it helps!
